### ISSUE TITLE
Server error 502

### ISSUE THREAD

**Issue by sarahheder** [dave-the-scientist/miphy#2]
Hi,

When I upload my files online, I get the following error: "Error uploading files; the server returned code 502." This is only happening with one of my sets of data. Have you encountered this error before, or do you have an idea of why this might be causing it? I've attached the files (with the gene tree as a .txt, as I can't attach the .nwk)

Thanks
[info213.txt](https://github.com/dave-the-scientist/miphy/files/3061873/info213.txt)
[hayden_OR213.txt](https://github.com/dave-the-scientist/miphy/files/3061875/hayden_OR213.txt)

**Comment by dave-the-scientist** [comment]
Hi, sorry for the late response (I just got back in the country). The issue appears to be that your info file and gene tree both contain entries from species "Pgi", but your species tree is missing it. That information should have appeared as part of the 502 error you saw, I'm looking into why it wasn't displayed.
