### ISSUE TITLE
Color code

### ISSUE THREAD

**Issue by francicco** [dave-the-scientist/miphy#4]
Hi,

Very nice tool indeed! Would it be possible to also set the species palette on the local version of the program?
Cheers
Feancesco

**Comment by dave-the-scientist** [comment]
Thanks, I'm always glad to see it getting used! 

I'm not too sure what you mean, are you asking for the ability to change the colour of individual species on the tree? Both the local and online versions should already have that functionality. To do so, check the "Display options" box below the tree. Just below the "Bar chart height" you should see a dropdown menu listing all of the species in your tree. After picking one, you can set the colour associated with that species with the coloured box beside the dropdown menu. After that press the "Redraw Tree" button and you should see the changes.

I hope that helps, and please do let me know if you have other questions.
Cheers,
Dave

**Comment by francicco** [comment]
Hi Dave,

Yes, exactly what I meant. But I was thinking to set the color code directly from the command-line. I have to analyse different trees always with the same customised colors.
Cheers
F

**Comment by dave-the-scientist** [comment]
Ah I see, that makes sense, and I see why you'd want to do that using command line. 
What about if it was an option in the info file? So that file would contain the species tree, the species assignments for the genes, and a 3rd field that allowed you to set the colour associated with each species? You could just add that text to every info file you need to analyze. I could implement that without much trouble, do you think it would be a good solution for you?

**Comment by francicco** [comment]
That would be just perfect!!!!!
F

**Comment by dave-the-scientist** [comment]
Ok, I've implemented that, and you should be able to install the latest version (1.1.0) from the releases page. The README now explains how to use it, but this is what it would look like for the "ugts_info.txt" file that is discussed on the tutorial page; just add this to the bottom:

[species colours]
C.remanei = #A1E8FF
C.briggsae = #A1FFA1
C.brenneri = #F4ED78
C.elegans = 255,87,51

As you see, the species names here must exactly match the species names in the species tree and in the species mapping sections. Colours can be specified using 3- or 6-digit hex notation, or by comma-separated RGB values.

I hope this helps! Let me know if you run into any issues or if you have other suggestions.
Cheers,
Dave

**Comment by francicco** [comment]
Wonderfull, thanks!!!!
F
