### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by alex-dal** [dave-the-scientist/miphy#6]
Hi,

I get an error 502 when I upload these files to the online server. I've made sure my species names don't contain spaces, and my gene tree is rooted. I'm not sure what kind of other formatting errors to look for.

Thanks for helping,
Alex

[het_protein_tree_rerooted2.txt](https://github.com/dave-the-scientist/miphy/files/11801453/het_protein_tree_rerooted2.txt)
[asp_info.txt](https://github.com/dave-the-scientist/miphy/files/11801454/asp_info.txt)

**Comment by dave-the-scientist** [comment]
Hi Alex,
For whatever reason, it seems that your gene tree has 1 more closing bracket ")" than it does opening brackets "(", and that's causing the "malformed tree" error. I'm guessing it happened during the rooting process. If you delete the final ")" character from the gene tree file, the one just before the ";" character, the software will load a tree with 2315 leaves (I assume that is the correct size?). 

However, when I looked at your tree, while it is rooted but it doesn't appear to be rooted in any particular way. This can affect the MIPhy analysis, and definitely affects how easy it is for you to interpret. Just eyeballing it I don't see an obvious outgroup, so "rooting by midpoint" is probably what you want to do. Many phylogenetic tree viewing programs can do this for you, including the popular FigTree, or the online tool Navargator (https://www.compsysbio.org/navargator/). Navargator is another piece of my software (not yet published or documented), that allows you to do a bunch of phylogenetic tasks. You can find this rooting function in the "Tree manipulations" section. You'll want to do that for any tree you generate, and it's usually a good idea to use the "Re-order nodes" function as well. Then you can download the newly rooted tree under the "Export data" section. I've done that and attached the tree for you here.
[het_protein_tree_rerooted3.txt](https://github.com/dave-the-scientist/miphy/files/11807350/het_protein_tree_rerooted3.txt)

Looking at that tree, it has some extremely long distances. The two most extreme branches (sequences 10622 & 154539) are pretty suspicious to me, so you might want to re-check your sequence alignment to see if there is anything wrong with them. I'm guessing you might want to remove them and then re-make your gene tree, as annoying as that can be.

Unfortunately there are also some issues with your info file. I see the program complaining about 11 species: A._cremei, A._clavatus, A._udagawe, A._fumigatus, A._ochraceoroseus, A._acristulatus, A._kawaachi, A._bertholletiae, A._pseudonomiae, A._nomiae, A._parvisclerotigenes. I quickly checked two, and I see A._cremei in the species tree and in the Colours section, but you do not have any genes assigned to it in the Species assignment section. I see A._parvisclerotigenes in the species tree and Colours sections, but in the assignment section you appear to have called it "A._parvisclerotigenus". The names must all match for the program to work.

Hopefully that will help you to get going with MIPhy.
Cheers,
Dave

**Comment by alex-dal** [comment]
That's really helpful! I also found a few spelling mistakes in species names. Thank you so much
